# Workflow to deploy with IG Publisher to the hl7austria.github.io repository

name: IGPublisher

# Run on updates to the master
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout the implementation guide
      uses: actions/checkout@v2
      with:
        repository: HL7Austria/hl7-at-fhir-profiles
        path: .

    - name: Download IG Publisher
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HL7/fhir-ig-publisher
        tag: '1.1.34'
        path: .
        file: publisher.jar

    - name: Run IG Publisher
      env: 
        DISPLAY: :0.0
      run: |
        java -jar publisher.jar -Djava.awt.headless=true
        
    - name: Deploy Implementation Guide
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./public # TODO publish correct folder
        exclude_assets: 'input_cache/*' 
