# Workflow to create a landing page for the ig publisher based on the libraries present on server

name: UpdateIndex

# Run on updates to the master
on:
  push:
    branches: [ pages ]
  pull_request:
    branches: [ pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the implementation guide
      uses: actions/checkout@v2
      with:
        repository: HL7Austria/hl7austria.github.io
        path: .

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Execute Update Script 
      run: |
        python update.py
